# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_auto_20170831_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lightshowstep',
            unique_together=set([('show', 'light', 'order')]),
        ),
    ]
