# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0003_auto_20170831_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightshowstep',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='lightshowstep',
            name='blue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lightshowstep',
            name='green',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lightshowstep',
            name='light',
            field=models.IntegerField(choices=[(1, {b'b': 37, b'g': 35, b'r': 33}), (2, {b'b': 40, b'g': 38, b'r': 36})]),
        ),
        migrations.AlterField(
            model_name='lightshowstep',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lightshowstep',
            name='red',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
