# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_auto_20171024_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightshow',
            name='light',
            field=models.IntegerField(blank=True, choices=[(1, {b'b': 37, b'g': 35, b'r': 33}), (2, {b'b': 40, b'g': 38, b'r': 36})], null=True),
        ),
        migrations.AlterField(
            model_name='lightshowstep',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='controls.LightShow'),
        ),
    ]
